### ISSUE TITLE
README crate badge sends to "Page removed"

### ISSUE THREAD

**Issue by dasm** [pytest-dev/pytest-cloud#13]
When clicked on button for `pypi` it redirected me to non existing website.
```
Sorry, the page you requested has been permanently removed.
```

**Comment by dasm** [comment]
I would submit the change by myself, but I'm not sure where it should be pointing to.

**Comment by bubenkoff** [comment]
to the pypi then

**Comment by dasm** [comment]
Changed url to pypi.
